parameters:
#    guigui_blog.example.class: Guigui\BlogBundle\Example

services:
#    guigui_blog.example:
#        class: %guigui_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
