<?php

namespace Guigui\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleSkillRepository extends EntityRepository
{
}
